# Generated by Django 4.0.4 on 2022-06-14 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_participant_tag_evidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='tag',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app1.tag'),
            preserve_default=False,
        ),
    ]
