# Generated by Django 4.0.4 on 2022-06-14 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_evidence_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evidence',
            name='tag',
        ),
        migrations.AddField(
            model_name='evidence',
            name='tags',
            field=models.ManyToManyField(to='app1.tag'),
        ),
    ]
