# Generated by Django 4.0.4 on 2022-06-15 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_remove_evidence_tag_evidence_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='name',
            field=models.IntegerField(),
        ),
    ]
